name: 📑 Updating pairs lists
on:
  schedule:
    - cron: '0 0 * * Mon'
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      if: "!contains(github.event.head_commit.message, '[bot] - Update lists')"
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        - name: GoSetup
          uses: actions/setup-go@v3
          with:
           go-version-file: './go.mod'
           go-version: '1.19.3'
        - name: run
          run: >
            RPC_URI_FOR_1=${{ secrets.RPC_URI_FOR_1 }} 
            RPC_URI_FOR_10=${{ secrets.RPC_URI_FOR_10 }} 
            RPC_URI_FOR_56=${{ secrets.RPC_URI_FOR_56 }} 
            RPC_URI_FOR_100=${{ secrets.RPC_URI_FOR_100 }} 
            RPC_URI_FOR_137=${{ secrets.RPC_URI_FOR_137 }} 
            RPC_URI_FOR_250=${{ secrets.RPC_URI_FOR_250 }} 
            RPC_URI_FOR_42161=${{ secrets.RPC_URI_FOR_42161 }} 
            RPC_URI_FOR_43114=${{ secrets.RPC_URI_FOR_43114 }} 
            go run ./generators uniswap-pairs sushiswap-pairs
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -a -m "[bot] - Update lists"
        - name: Temporarily disable "include administrators" branch protection
          uses: benjefferies/branch-protection-bot@master
          if: always()
          with:
           access_token: ${{ secrets.ACCESS_TOKEN }}
           branch: ${{ github.event.repository.default_branch }}
           enforce_admins: false
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.ACCESS_TOKEN }}
            branch: ${{ github.ref }}
        - name: Enable "include administrators" branch protection
          uses: benjefferies/branch-protection-bot@master
          if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
          with:
            access_token: ${{ secrets.ACCESS_TOKEN }}
            owner: migratooor
            repo: tokenLists
            branch: ${{ github.event.repository.default_branch }}
            enforce_admins: true
